### ISSUE TITLE
uncomfortable view showing while dragging up and down,, 

### ISSUE THREAD

**Issue by AqibShxhzad** [Ramotion/navigation-toolbar-android#16] opened 2020-01-09 11:51 UTC
you can see attached images for further help

![Screenshot_2020-01-09-16-43-05](https://user-images.githubusercontent.com/58720827/72065514-3cb91300-3300-11ea-94dc-7ddc4dc234e6.png)
![Screenshot_2020-01-09-16-43-10](https://user-images.githubusercontent.com/58720827/72065515-3cb91300-3300-11ea-8a99-93bef3b79383.png)

**Comment by golovin47** [comment] 2020-01-09 11:53
Duplicate of #13.

**Closed as completed by golovin47** 2020-01-09 11:53 UTC

**Comment by AqibShxhzad** [comment] 2020-01-09 11:56
so why are you closing...??? when it haven't fix yet.
